---
- name: creates directory
  file:
    path: /var/portainer
    state: directory
    owner: root
    group: docker
    mode: 0740

- name: create admin_password file
  template:
    src: templates/admin_password.j2
    dest: /var/portainer/admin_password
    owner: root
    group: docker
    mode: 0640